### ISSUE TITLE
module = importlib.import_module(module_name)

### ISSUE THREAD

**Issue by chl916185** [pytorch/serve#250]
> 
(pytorch_1.5) chl@chl:~/work_files/AI_project/embedded_project/serve_master$ torchserve --start --model-store model_store --models densenet161=densenet161.mar
(pytorch_1.5) chl@chl:~/work_files/AI_project/embedded_project/serve_master$ 2020-04-22 23:46:39,358 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
2020-04-22 23:46:39,583 [INFO ] main org.pytorch.serve.ModelServer - 
TS Home: /home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages
Current directory: /media/chl/workfiles/AI_project/embedded_project/serve_master
Temp directory: /tmp
Number of GPUs: 1
Number of CPUs: 4
Max heap size: 1744 M
Python executable: /home/chl/.conda/envs/pytorch_1.5/bin/python
Config file: logs/config/20200422234637146-shutdown.cfg
Inference address: http://127.0.0.1:8080
Management address: http://127.0.0.1:8081
Model Store: /media/chl/workfiles/AI_project/embedded_project/serve_master/model_store
Initial Models: densenet161=densenet161.mar
Log dir: /media/chl/workfiles/AI_project/embedded_project/serve_master/logs
Metrics dir: /media/chl/workfiles/AI_project/embedded_project/serve_master/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
2020-04-22 23:46:39,587 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {
  "name": "20200422234637146-shutdown.cfg",
  "modelCount": 1,
  "created": 1587570397146,
  "models": {
    "densenet161": {
      "1.0": {
        "defaultVersion": true,
        "marName": "densenet161.mar",
        "minWorkers": 1,
        "maxWorkers": 1,
        "batchSize": 1,
        "maxBatchDelay": 100,
        "responseTimeout": 120
      }
    }
  }
}
2020-04-22 23:46:39,595 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validating snapshot 20200422234637146-shutdown.cfg
2020-04-22 23:46:39,596 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validated snapshot 20200422234637146-shutdown.cfg
2020-04-22 23:46:41,545 [INFO ] main org.pytorch.serve.archive.ModelArchive - model folder already exists: 3f8a492de8e1f456d344117419586f8f312d316c
2020-04-22 23:46:41,556 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model densenet161
2020-04-22 23:46:41,556 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model densenet161
2020-04-22 23:46:41,556 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model densenet161 loaded.
2020-04-22 23:46:41,556 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: densenet161, count: 1
2020-04-22 23:46:41,572 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model densenet161
2020-04-22 23:46:41,575 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-04-22 23:46:41,644 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://127.0.0.1:8080
2020-04-22 23:46:41,644 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-04-22 23:46:41,645 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://127.0.0.1:8081
Model server started.
2020-04-22 23:46:41,658 [WARN ] pool-2-thread-1 org.pytorch.serve.metrics.MetricCollector - worker pid is not available yet.
2020-04-22 23:46:41,705 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-04-22 23:46:41,705 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]13069
2020-04-22 23:46:41,705 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-22 23:46:41,706 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.2
2020-04-22 23:46:41,706 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change null -> WORKER_STARTED
2020-04-22 23:46:41,709 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-04-22 23:46:41,719 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-04-22 23:46:41,738 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process die.
2020-04-22 23:46:41,738 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:41,739 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "**/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 90, in load
2020-04-22 23:46:41,739 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-04-22 23:46:41,739 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:41,739 [INFO ] W-9000-densenet161_1.0-stdout** org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:41,739 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
2020-04-22 23:46:41,740 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
2020-04-22 23:46:41,740 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
2020-04-22 23:46:41,740 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'image_classifier'
2020-04-22 23:46:41,740 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:41,740 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2020-04-22 23:46:41,741 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:41,741 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:41,741 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 163, in <module>
2020-04-22 23:46:41,741 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-04-22 23:46:41,742 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 141, in run_server
2020-04-22 23:46:41,742 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-04-22 23:46:41,742 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 105, in handle_connection
2020-04-22 23:46:41,743 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-04-22 23:46:41,743 [INFO ] epollEventLoopGroup-4-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-04-22 23:46:41,743 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-22 23:46:41,746 [WARN ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: densenet161, error: Worker died.
2020-04-22 23:46:41,747 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-04-22 23:46:41,743 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 83, in load_model
2020-04-22 23:46:41,748 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-04-22 23:46:41,748 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 93, in load
2020-04-22 23:46:41,748 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name, 'ts.torch_handler')
2020-04-22 23:46:41,748 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:41,749 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-04-22 23:46:41,749 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:41,749 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 973, in _gcd_import
2020-04-22 23:46:41,750 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 923, in _sanity_check
2020-04-22 23:46:41,750 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - SystemError: Parent module 'ts.torch_handler' not loaded, cannot perform relative import
2020-04-22 23:46:41,757 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:chl,timestamp:1587570401
2020-04-22 23:46:41,757 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:8.90652084350586|#Level:Host|#hostname:chl,timestamp:1587570401
2020-04-22 23:46:41,757 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:19.06207275390625|#Level:Host|#hostname:chl,timestamp:1587570401
2020-04-22 23:46:41,758 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:68.2|#Level:Host|#hostname:chl,timestamp:1587570401
2020-04-22 23:46:41,758 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:1356.62109375|#Level:Host|#hostname:chl,timestamp:1587570401
2020-04-22 23:46:41,759 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:5491.6875|#Level:Host|#hostname:chl,timestamp:1587570401
2020-04-22 23:46:41,759 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:82.7|#Level:Host|#hostname:chl,timestamp:1587570401
2020-04-22 23:46:42,854 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-04-22 23:46:42,855 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]13108
2020-04-22 23:46:42,855 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-22 23:46:42,855 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-04-22 23:46:42,857 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-04-22 23:46:42,857 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.2
2020-04-22 23:46:42,870 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-04-22 23:46:42,873 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process die.
2020-04-22 23:46:42,873 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:42,873 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 90, in load
2020-04-22 23:46:42,873 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-04-22 23:46:42,873 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:42,873 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:42,873 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'image_classifier'
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:42,874 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 163, in <module>
2020-04-22 23:46:42,875 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-04-22 23:46:42,875 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 141, in run_server
2020-04-22 23:46:42,875 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-04-22 23:46:42,876 [INFO ] epollEventLoopGroup-4-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-04-22 23:46:42,877 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 105, in handle_connection
2020-04-22 23:46:42,877 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-22 23:46:42,878 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-04-22 23:46:42,879 [WARN ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: densenet161, error: Worker died.
2020-04-22 23:46:42,880 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-04-22 23:46:42,880 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-04-22 23:46:42,880 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 83, in load_model
2020-04-22 23:46:42,881 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-04-22 23:46:42,881 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 93, in load
2020-04-22 23:46:42,881 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name, 'ts.torch_handler')
2020-04-22 23:46:42,881 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:42,881 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:42,881 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 973, in _gcd_import
2020-04-22 23:46:42,882 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 923, in _sanity_check
2020-04-22 23:46:42,882 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - SystemError: Parent module 'ts.torch_handler' not loaded, cannot perform relative import
2020-04-22 23:46:43,980 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-04-22 23:46:43,980 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]13136
2020-04-22 23:46:43,980 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-22 23:46:43,980 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-04-22 23:46:43,980 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.2
2020-04-22 23:46:43,980 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-04-22 23:46:43,981 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-04-22 23:46:43,984 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process die.
2020-04-22 23:46:43,988 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:43,988 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 90, in load
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'image_classifier'
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:43,989 [INFO ] epollEventLoopGroup-4-3 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2020-04-22 23:46:43,989 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-22 23:46:43,990 [WARN ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: densenet161, error: Worker died.
2020-04-22 23:46:43,990 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-04-22 23:46:43,989 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 2 seconds.
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 163, in <module>
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 141, in run_server
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 105, in handle_connection
2020-04-22 23:46:43,990 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-04-22 23:46:43,991 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 83, in load_model
2020-04-22 23:46:43,991 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-04-22 23:46:43,991 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 93, in load
2020-04-22 23:46:43,991 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name, 'ts.torch_handler')
2020-04-22 23:46:43,991 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:43,991 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:43,991 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 973, in _gcd_import
2020-04-22 23:46:43,992 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 923, in _sanity_check
2020-04-22 23:46:43,992 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - SystemError: Parent module 'ts.torch_handler' not loaded, cannot perform relative import
2020-04-22 23:46:46,090 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-04-22 23:46:46,091 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]13188
2020-04-22 23:46:46,091 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-22 23:46:46,091 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-04-22 23:46:46,091 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.2
2020-04-22 23:46:46,091 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-04-22 23:46:46,092 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-04-22 23:46:46,093 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process die.
2020-04-22 23:46:46,094 [INFO ] epollEventLoopGroup-4-4 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 90, in load
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'image_classifier'
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2020-04-22 23:46:46,094 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 163, in <module>
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 141, in run_server
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 105, in handle_connection
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 83, in load_model
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 93, in load
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name, 'ts.torch_handler')
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:46,095 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 973, in _gcd_import
2020-04-22 23:46:46,096 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 923, in _sanity_check
2020-04-22 23:46:46,096 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - SystemError: Parent module 'ts.torch_handler' not loaded, cannot perform relative import
2020-04-22 23:46:46,096 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-22 23:46:46,096 [WARN ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: densenet161, error: Worker died.
2020-04-22 23:46:46,096 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-04-22 23:46:46,097 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 3 seconds.
2020-04-22 23:46:49,192 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-04-22 23:46:49,192 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]13277
2020-04-22 23:46:49,192 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-22 23:46:49,192 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-04-22 23:46:49,192 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.2
2020-04-22 23:46:49,193 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-04-22 23:46:49,194 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-04-22 23:46:49,195 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process die.
2020-04-22 23:46:49,195 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:49,195 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 90, in load
2020-04-22 23:46:49,195 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:49,196 [INFO ] epollEventLoopGroup-4-5 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:49,196 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
2020-04-22 23:46:49,196 [WARN ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: densenet161, error: Worker died.
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
2020-04-22 23:46:49,196 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'image_classifier'
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 5 seconds.
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:49,196 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 163, in <module>
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 141, in run_server
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 105, in handle_connection
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 83, in load_model
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 93, in load
2020-04-22 23:46:49,197 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name, 'ts.torch_handler')
2020-04-22 23:46:49,198 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:49,198 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:49,198 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 973, in _gcd_import
2020-04-22 23:46:49,198 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 923, in _sanity_check
2020-04-22 23:46:49,198 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - SystemError: Parent module 'ts.torch_handler' not loaded, cannot perform relative import
2020-04-22 23:46:54,307 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-04-22 23:46:54,307 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]13427
2020-04-22 23:46:54,307 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-22 23:46:54,307 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-04-22 23:46:54,307 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.2
2020-04-22 23:46:54,307 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-04-22 23:46:54,308 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process die.
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 90, in load
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
2020-04-22 23:46:54,310 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
2020-04-22 23:46:54,311 [INFO ] epollEventLoopGroup-4-6 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'image_classifier'
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - 
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 163, in <module>
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-04-22 23:46:54,311 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-22 23:46:54,311 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 141, in run_server
2020-04-22 23:46:54,312 [WARN ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: densenet161, error: Worker died.
2020-04-22 23:46:54,312 [DEBUG] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-densenet161_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 8 seconds.
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 105, in handle_connection
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_service_worker.py", line 83, in load_model
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/site-packages/ts/model_loader.py", line 93, in load
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name, 'ts.torch_handler')
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/chl/.conda/envs/pytorch_1.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-04-22 23:46:54,312 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 973, in _gcd_import
2020-04-22 23:46:54,313 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 923, in _sanity_check
2020-04-22 23:46:54,313 [INFO ] W-9000-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - SystemError: Parent module 'ts.torch_handler' not loaded, cannot perform relative import

**Comment by lokeshgupta1975** [comment]
@chl916185 Issue acknowledged. Someone will take a look at it today. Just to confirm, did you just use this command to get this error:
`torchserve --start --model-store model_store --models densenet161=densenet161.mar`

**Comment by dhanainme** [comment]
Also can you confirm if you have created a folder **model_store** & you have densenet161.mar inside the folder as described https://aws.amazon.com/blogs/aws/announcing-torchserve-an-open-source-model-server-for-pytorch/

**Comment by dhanainme** [comment]
This may have been fixed with https://github.com/pytorch/serve/pull/248.

**Comment by fbbradheintz** [comment]
#248 does not fix this (and in fact was incorrect). The problem appears to be the Python path or environment - certain imports are failing, e.g:
```
org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'image_classifier'
```
and
```
org.pytorch.serve.wlm.WorkerLifeCycle - SystemError: Parent module 'ts.torch_handler' not loaded, cannot perform relative import
```

**Comment by mohammedayub44** [comment]
@dhanainme  @fbbradheintz  I can confirm that I see the same error when I load a custom model inside my custom_handler.py file. 
The import runs fine when I run it outside on the Jypyter notebook.

```python3
module_path = os.path.abspath(os.path.join('../../../../'))
if module_path not in sys.path:
    sys.path.append(module_path+"/SSDCNet")

...
from Network.SSDCNet import SSDCNet_classify
``` 

Error:

```python

   File "/tmp/models/58eb8da6a1c8563374304a9fc66b2788a9c9c440/crdcnt_handler.py", line 9, in <module>
   from crowdmodel import CrowdCounter
   File "/tmp/models/58eb8da6a1c8563374304a9fc66b2788a9c9c440/crowdmodel.py", line 8, in <module>
    from Network.SSDCNet import SSDCNet_classify
ModuleNotFoundError: No module named 'Network'
```

Here is the log file:  
[server_log3.txt](https://github.com/pytorch/serve/files/4596700/server_log3.txt)
 
Not sure if I'm missing something.

Thanks !

**Comment by harshbafna** [comment]
@mohammedayub44 : This is a different error from the original error as you are using a custom handler and will need the mar file you are using.

Could you please create a new ticket for this using the following template :

https://github.com/pytorch/serve/blob/staging_0_1_1/ISSUE_TEMPLATE/bug_template.md

**Comment by mohammedayub44** [comment]
@harshbafna Np. Raised #314  
Temporarily fixed using `PYTHONPATH` instead of adding to `sys.path` before running the serve command.

**Comment by harshbafna** [comment]
@chl916185 : From the logs provided it can be observed that you are using conda environment with python 3.6. 

> org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.2


However, as documented [here](https://github.com/pytorch/serve#install-torchserve)

> Note: For Conda, Python 3.8 is required to run Torchserve

Could you please confirm?

**Comment by maaquib** [comment]
Closig this. @mohammedayub44 Please reopen if this is still an issue

**Comment by mohammedayub44** [comment]
@maaquib  Thanks. Providing the Python path to the model defn. fixes it for me.
